# Car Details from Car Dekho website

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')

In [3]:
df.head()

                       name  year  ...  transmission         owner
0             Maruti 800 AC  2007  ...        Manual   First Owner
1  Maruti Wagon R LXI Minor  2007  ...        Manual   First Owner
2      Hyundai Verna 1.6 SX  2012  ...        Manual   First Owner
3    Datsun RediGO T Option  2017  ...        Manual   First Owner
4     Honda Amaze VX i-DTEC  2014  ...        Manual  Second Owner

[5 rows x 8 columns]

In [4]:
df.shape

(4340, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [6]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [7]:
labels=df[['selling_price']]
labels.head()

   selling_price
0          60000
1         135000
2         600000
3         250000
4         450000

In [8]:
features = df[['year','km_driven']]
features.head()

   year  km_driven
0  2007      70000
1  2007      50000
2  2012     100000
3  2017      46000
4  2014     141000

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.15)

In [13]:
X_train.shape, X_test.shape

((3689, 2), (651, 2))

In [14]:
y_train.shape, y_test.shape

((3689, 1), (651, 1))

In [15]:
from sklearn import linear_model

In [16]:
model = linear_model.LinearRegression()

In [17]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
from sklearn.metrics import r2_score

##Training R2 Score

In [19]:
predictions = model.predict(X_train)

In [20]:
r2 = r2_score(y_train, predictions)
print("R2 Score :", r2)

R2 Score : 0.16904111298186908

##Testing R2 Score

In [21]:
predictions = model.predict(X_test)

r2 = r2_score(y_test, predictions)
print("R2 Score :", r2)

R2 Score : 0.18865531111151523